services:
  openvscode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openvscode-server
    ports:
      - "3000:3000"
    environment:
      - DISABLE_TERMINAL=true
    volumes:
      - .:/home/workspace:cached
    command: ["openvscode-server",
     "--without-connection-token",
     "--default-workspace", "/home/workspace/files",
     "--default-folder", "/home/workspace/files",
     "--install-extension", "/tmp/exts/layout-builder-0.0.1.vsix",
     "--start-server"
    ]
