services:
  openvscode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openvscode-server
    environment:
      - DISABLE_TERMINAL=true
    volumes:
      - .:/home/workspace:cached
      - ./custom-workplace-settings.json:/home/workspace/.vscode/custom-workplace-settings.json
      - ./custom-user-settings.json:/home/workspace/.vscode/custom-user-settings.json
    command: ["openvscode-server",
     "--without-connection-token",
     "--default-workspace", "/home/workspace/files",
     "--default-folder", "/home/workspace/files",
     "--install-extension", "/tmp/exts/layout-builder-0.0.1.vsix",
     "--install-extension", "/tmp/exts/auto-config-0.0.1.vsix",
     "--install-extension", "/tmp/exts/weaver-0.0.1.vsix",
     "--disable-workspace-trust",
     "--start-server"
    ]
