services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOOL: ${TOOL}
    environment:
      - TOOL=${TOOL}
    ports:
      - 8000:4000
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "server.js"]