services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOOL: ${TOOL}
    environment:
      - TOOL=${TOOL}
    ports:
      - 8000:4000
    command: ["npm", "start"]