services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOOL: kadabra
    ports:
      - 8080:4000
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "server.js"]